### ISSUE TITLE
XmlSettingsProvider.CopyObject() problem with List<T> member 

### ISSUE THREAD

**Issue by joonhwan** [thomaslevesque/NSettings#1]
Hi, I've been looking for a nice and simple settings library that I can started with and understand easily(Some nice lib out there but with moderate complexity) and yours is too good enough!

I'm trying to retrive settings of following type but MonitorTxConfigs could not be retrieved correctly due to CopyObject() impl. 

If I init 'MonitorTxConfigs' member as null, problem was solved, but I want this prop to be initialized in the same time. 

Any Hint?

```

    public class RemoteKvmConfig
    {
        public string Ip { get; set; }
        public int Port { get; set; }
        public List<MonitorTxConfig> MonitorTxConfigs { get; set; } 

        public RemoteKvmConfig()
        {
            Ip = "localhost";
            Port = 8080;
            MonitorTxConfigs = new List<MonitorTxConfig>();
        }
    }

```

**Comment by thomaslevesque** [comment]
Hi,

Sorry for the delay, I was on vacation...

I don't understand what your problem is exactly. Are you saying that the content of `MonitorTxConfigs` is not properly loaded from the settings file?

**Comment by joonhwan** [comment]
My xml `config.conf' follows

``` xml
<Settings>
  <RemoteKvmConfig>
    <Ip>localhost</Ip>
    <Port>8080</Port>
    <MonitorTxConfigs>
      <MonitorTxConfig>
        <Name>Tx#1</Name>
        <Ip>localHost</Ip>
        <Port>9000</Port>
      </MonitorTxConfig>
      <MonitorTxConfig>
        <Name>Tx#2</Name>
        <Ip>localHost</Ip>
        <Port>9000</Port>
      </MonitorTxConfig>
    </MonitorTxConfigs>
  </RemoteKvmConfig>
  <AkkaConfig>
    <HostPort>0</HostPort>
  </AkkaConfig>
</Settings>
```

and I tried to load this like ...

``` c#
            var storage = new FileStreamStorageProvider("config.conf");
            var provider = new XmlSettingsProvider(storage);
            provider.Load();
            var kvmConfig= provider.GetSettings<RemoteKvmConfig>();
```

but `kvmConfg.MonitorTxConfigs` list is empty.

On the other hand, from the `XmlSettingsProvider.cs` ... 

``` c#
        private static void CopyObject(object source, object destination)
        {
            var type = source.GetType();
            foreach (var property in type.GetRuntimeProperties())
            {
                if (!property.CanWrite || !property.CanRead)
                    continue;
                if (property.GetMethod.IsStatic)
                    continue;
                if (!property.GetMethod.IsPublic)
                    continue;
                if (property.GetIndexParameters().Any())
                    continue;

                object value = property.GetValue(source);
                object existingValue = null;
                if (!IsValue(property.PropertyType))
                    existingValue = property.GetValue(destination);

                if (existingValue == null)
                    property.SetValue(destination, value);
                else
                    CopyObject(value, existingValue);
            }
        }
```

When this guy do `CopyObject()` I confirmed `source` has been deserialized correctly but there seems to be problem while copying it into `destination` that is the final output.

What's the meaning of following `if``blocks? the`MonitorTxConfigs` list was handled incorrectly there.

```
               if (!IsValue(property.PropertyType))
                    existingValue = property.GetValue(destination);

                if (existingValue == null)
                    property.SetValue(destination, value);
                else
                    CopyObject(value, existingValue);
```

Maybe we need special 'CopyObject()' behavior for collection.

Thanks for reply.

**Comment by thomaslevesque** [comment]
Ah, I see... collections should be handled differently, but it's not currently implemented. `CopyObject` should check if it's a collection type, and copy the items accordingly.

Keep in mind that this project isn't a finished product... I started working on it a long time ago an never really completed it, which is why it's not on NuGet.

**Comment by thomaslevesque** [comment]
It should be fixed in [this branch](https://github.com/thomaslevesque/NSettings/tree/fix-load-collection-xml). Let me know if it works as expected, I'll merge it then.

**Comment by joonhwan** [comment]
Yes, you're right. and it works.

**Comment by thomaslevesque** [comment]
merged
